spring:
  profiles:
    active: dev

---
# 开发环境
server:
  port:8201
spring:
  profiles: dev
  application:
    name: springcloud-provider-user 

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
      
---
# 测试环境
server:
  port:8202
spring:
  profiles: test
  application:
    name: springcloud-provider-user 

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/      